-- CreateTables
CREATE TABLE IF NOT EXISTS `Category` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `imageUrl` VARCHAR(191),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `meta_title` VARCHAR(191),
  `meta_description` VARCHAR(191),
  `meta_keywords` VARCHAR(191),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Subcategory` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `imageUrl` VARCHAR(191),
  `categoryId` INTEGER NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `meta_title` VARCHAR(191),
  `meta_description` VARCHAR(191),
  `meta_keywords` VARCHAR(191),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`categoryId`) REFERENCES `Category`(`id`) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `CompanyDetails` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `headerImage` VARCHAR(191) NOT NULL,
  `favIcon` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ContactInfo` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `address` VARCHAR(191) NOT NULL,
  `website` VARCHAR(191) NOT NULL,
  `owner` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SocialMedia` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `facebook` VARCHAR(191),
  `instagram` VARCHAR(191),
  `twitter` VARCHAR(191),
  `tiktok` VARCHAR(191),
  `pinterest` VARCHAR(191),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `FacebookPixel` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `pixelCode` VARCHAR(191) NOT NULL,
  `pixelId` VARCHAR(191),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `AboutUs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ContactUs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `PrivacyPolicy` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `TermAndConditions` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ShippingPolicy` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ReturnAndExchangePolicy` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(191) NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Faq` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(191) NOT NULL,
  `answer` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;