'use client';

import React, { useEffect, useState } from 'react';
import TopBar from './components/TopBar';
import Header from './components/Header';
import BrowseCategories from './components/BrowseCategories';
import Footer from './components/Footer';
import '../globals.css';
import WhatsAppButton from './components/whatsappbutton';
import dynamic from 'next/dynamic';

// Dynamically import components that use browser APIs
const DynamicHeader = dynamic(() => import('./components/Header'), {
  ssr: false,
});

const CustomerLayout = ({ children }) => {
  const [isClient, setIsClient] = useState(false);
  const [pixelCode, setPixelCode] = useState('');

  useEffect(() => {
    setIsClient(true);

    const fetchPixelCode = async () => {
      try {
        const response = await fetch('/api/pixels');
        const data = await response.json();
        if (data?.data?.length > 0) {
          setPixelCode(data.data[0].pixelCode);
        }
      } catch (error) {
        console.error('Error fetching pixel code:', error);
      }
    };

    fetchPixelCode();
  }, []);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>QuickDelivery</title>
        <meta name="description" content="Generated by create next app" />
        {pixelCode && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                !function(f,b,e,v,n,t,s)
                {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)}(window,document,'script',
                'https://connect.facebook.net/en_US/fbevents.js');
                fbq('init', '${pixelCode}'); 
                fbq('track', 'PageView');
              `,
            }}
          />
        )}
      </head>
      <body>
        <div className="min-h-screen bg-white flex flex-col">
          <TopBar />
          <Header />
          <main className="flex-grow">
            {isClient && <WhatsAppButton />}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default CustomerLayout;
